### ISSUE TITLE
[BUG] 生成了除零操作的表达式，导致 Floating point exception (core dumped)

### ISSUE THREAD

**Issue by Jstar49** [Jstar49/C-star#5]
案例：
[main.txt](https://github.com/Jstar49/C-star/files/10209282/main.txt)  

在 x86 平台上编译：  

> \> gcc ./main.c 
> \> ./a.out
> Floating point exception (core dumped)

**Comment by Jstar49** [comment]
如何避免除零表达式的生成

**Comment by Jstar49** [comment]
Floating point exception 异常生成原因：https://www.ibm.com/docs/en/aix/7.2?topic=concepts-floating-point-exceptions

**Comment by SuperWildFireFox** [comment]
除了gcc等编译器造成的常量折叠等问题外，其他除零操作均可探测并用值+1规避。

**Comment by Jstar49** [comment]
SuperWildFireFox:cal_num
